import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@app/lib/AuthContext"; // Import AuthProvider
import Sidebar from "@app/components/Sidebar"; // Import nowego Sidebar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* AuthProvider otacza całą aplikację */}
        <AuthProvider>
          <div className="flex flex-row flex-1">
            <aside className="w-1/4 bg-gray-800 text-white p-4">
              <Sidebar />
            </aside>
            <main className="flex-1 bg-gray-100 p-4">{children}</main>
          </div>
          <footer className="bg-gray-800 text-white p-4 text-center">
            &copy; {new Date().getFullYear()} MyApp. All Rights Reserved.
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
